# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

## => Site Settings
title: Jw's
email: hanghur@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Random notes/thoughts on programming, machine learning, ethics and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jwhhh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-text-theme
text_skin: my_own_skin


## => Language and Timezone
lang: en
timezone: Australia/Sydney
repository: jwhhh/jwhhh.github.io
license: CC-BY-NC-4.0


## => Author and Social
author:
  name      : Jiawen
  url       : https://jwhhh.github.io
  avatar    : assets/apple-touch-icon.png
  # bio       : 
  email     : hanghur@gmail.com
  # douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : jwhhh
  github    : jwhhh


## => GitHub Repository
repository: jwhhh/jwhhh.github.io
repository_tree: main


## => Markdown Enhancements
mathjax: true
mathjax_autoNumber: false
# mermaid: true
# chart: true


## => Poginate
paginate: 8
paginate_path: /test/page:num


## => Build
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: false
      # license: true
      aside:
        toc: true
      # pageview: true


## => Search
search:
  provider: default


## => Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

data_dir: /_data

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
