# Setup
title: Jw's
tagline: random notes/thoughts on programming, machine learning, ethics and more.
url: ""
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# Options
theme: jekyll-text-theme


# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jiawen
  url: https://github.com/jwhhh
  email: hanghur@gmail.com

# Custom vars
# version: 0.1.0
